### ISSUE TITLE
NOTE_013 Note Save

### ISSUE THREAD

**Issue by manfrm10** [sw19-tug/morning01#23]
-) create central class for DB operations
-) find notes
-) update notes

**Comment by anhaupt** [comment]
I would suggest to use a Singelton for the DatabaseHelper. Make the DatabaseHelper constructor private and create instances of this class by using the getInstance method

**Comment by manfrm10** [comment]
We should avoid singleton classes because they are harder to test. The DatabaseHelper for example needs a context and it is a different context for production and testing: at production we use the MainActivity object and for tests we use `InstrumentationRegistry.getTargetContext() `

You can also find it on the slides:
- Avoid tightly coupling components.
- Avoid global variables!
- **Avoid Singleton!**
- Use dependency injection.
- Use mocking.
