### ISSUE TITLE
NOTE_038 Small Bug Fixes

### ISSUE THREAD

**Issue by manfrm10** [sw19-tug/morning01#94]
Acceptance Criteria:
- Set version to 1.0
- Fixed search bar description to also indicate that search by tag is possible.
- Fixed protected notes. When trying to protect a note, it was still showing up in the `notesListView `in `MainActivity`. This bug was probably introduced when fixing merge conflicts.
- The theme that was selected last is now saved and applied to the next opening of the application.
- Tags can't be edited for soft deleted notes.
- Fixed sporadic exception that was printed out in the logs due to `IntentReceivers`. 
- Refactored `NoteStorage `because there was one `getAll()` function which was redundant. This bug was probably introduced when fixing merge conflicts.
- Fixed layout of `TagActivity`. Added a `TextView` that tells the user how to change the color of the `NoteTag`. Reduced dimensions of `ImageView` that shows the current color. Changed two string values so that they make more sense.
- Code reformatting
- Drop all tables on upgrade

**Comment by agape94** [comment]
For now i don't see any other obvious problems. 
On my device all the tests are working.

I have a question about the tests: 
- `checkIfNoteIsNotVisibleAfterSettingToProtected()`
- `checkIfNoteIsNotVisibleAfterSettingToUnprotected()`
To me, these tests seem to be doing the exact same thing. Correct me if I am wrong :) .
